import type {
  AdvisorProfile,
  AdvisorReview,
  AppState,
  JobContract,
  ListedRole,
  ManagerProfile,
  OwnerProfile,
  Persona,
  SoftwareTaxonomy,
} from "./types";

const portrait = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=400&h=400&q=80`;

export const personas: Persona[] = [
  {
    id: "persona-owner",
    role: "owner",
    label: "Motel Owner",
    name: "Helen Walsh",
    subtitle: "The Highway Rest · Dubbo NSW",
    photoUrl: portrait("photo-1544005313-94ddf0286df2"),
    ownerId: "owner-helen",
  },
  {
    id: "persona-verified",
    role: "verified_manager",
    label: "Premium Manager",
    name: "Marcus & Priya Brennan",
    subtitle: "Couple · GuestPoint · NSW / QLD liquor",
    photoUrl: portrait("photo-1500648767791-00dcc994a43e"),
    managerId: "mgr-brennan",
  },
  {
    id: "persona-unverified",
    role: "unverified_manager",
    label: "Non-vetted Manager",
    name: "Jamie Cole",
    subtitle: "Solo · Pending owner references",
    photoUrl: portrait("photo-1507003211169-0a1dd7228f2d"),
    managerId: "mgr-jamie",
  },
  {
    id: "persona-admin",
    role: "admin",
    label: "System Admin",
    name: "Alex Rivera",
    subtitle: "Reference, software & dispute oversight",
    photoUrl: portrait("photo-1573496359142-b8d87734a5a2"),
  },
];

export const defaultTaxonomy: SoftwareTaxonomy = {
  pms: [
    "GuestPoint",
    "Cloudbeds",
    "RMS",
    "Resly",
    "Booking247",
    "SiteMinder",
    "Little Hotelier",
    "Opera",
  ],
  pos: ["Lightspeed", "H&L", "Impos", "Square", "Toast", "Idealpos"],
  hr: ["Deputy", "Tanda", "Employment Hero", "Xero Payroll", "FoundU"],
  customQueue: [
    {
      id: "sw-1",
      name: "RoomMaster",
      category: "PMS",
      submittedBy: "Jamie Cole",
      status: "Pending",
    },
    {
      id: "sw-2",
      name: "Mews",
      category: "PMS",
      submittedBy: "Sophie Nguyen",
      status: "Pending",
    },
  ],
};

export const seedManagers: ManagerProfile[] = [
  {
    id: "mgr-brennan",
    name: "Marcus Brennan",
    email: "marcus.priya@motelmanagers.au",
    phone: "0412 880 114",
    location: "Dubbo, NSW",
    state: "NSW",
    lat: -32.2569,
    lng: 148.6011,
    photoUrl: portrait("photo-1500648767791-00dcc994a43e"),
    bio: "Highway motel couple with 11 years across western NSW and southern QLD. Night audit, breakfast service and owner-relief cover without drama.",
    rightToWork: "Australian Citizen",
    experience: "5+ years",
    profileType: "Couple",
    partnerName: "Priya Brennan",
    partnerBio:
      "Front office lead with GuestPoint channel mapping, housekeeping standards and liquor-licensed bar service.",
    partnerExperience: "5+ years",
    partnerPhotoUrl: portrait("photo-1544005313-94ddf0286df2"),
    partnerRightToWork: "Australian Citizen",
    preferredLocations: ["NSW", "QLD", "Nationwide"],
    preferredJobTypes: ["Relief Couple", "Permanent Couple"],
    liquorLicensing: true,
    liquorStates: ["NSW", "QLD"],
    eventsExperience: true,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["GuestPoint", "RMS", "SiteMinder"],
    softwarePOS: ["H&L", "Idealpos"],
    softwareHR: ["Deputy", "Xero Payroll"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-b1",
        businessName: "Castlereagh Motor Inn",
        contactPerson: "Diane Croft",
        phone: "02 6882 4411",
        email: "diane@castlereaghmotel.com.au",
        status: "Verified",
      },
      {
        id: "ref-b2",
        businessName: "Warrego Highway Motel",
        contactPerson: "Paul Nguyen",
        phone: "07 4632 1090",
        email: "paul@warregomotel.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-09-12", "2026-09-13", "2026-12-24", "2026-12-25"],
    completedShifts: 28,
  },
  {
    id: "mgr-jamie",
    name: "Jamie Cole",
    email: "jamie.cole@outlook.com",
    phone: "0438 221 907",
    location: "Toowoomba, QLD",
    state: "QLD",
    lat: -27.5598,
    lng: 151.9507,
    photoUrl: portrait("photo-1507003211169-0a1dd7228f2d"),
    bio: "Relief manager moving from pubs into motels. Strong breakfast and grounds presentation. Two owner references awaiting verification.",
    rightToWork: "Australian Citizen",
    experience: "1-2 years",
    profileType: "Solo",
    preferredLocations: ["QLD", "NSW"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["QLD"],
    eventsExperience: false,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: false },
    softwarePMS: ["Cloudbeds", "Booking247"],
    softwarePOS: ["Square"],
    softwareHR: ["Tanda"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: false },
    references: [
      {
        id: "ref-j1",
        businessName: "Rangeview Motel",
        contactPerson: "Karen Mills",
        phone: "07 4638 2201",
        email: "gm@rangeviewmotel.com.au",
        status: "Pending",
      },
      {
        id: "ref-j2",
        businessName: "Picnic Point Motor Lodge",
        contactPerson: "Steve Hart",
        phone: "07 4632 5510",
        email: "steve@picnicpointlodge.com.au",
        status: "Pending",
      },
    ],
    isVerified: false,
    blockoutDates: ["2026-10-01", "2026-10-02"],
    completedShifts: 2,
  },
  {
    id: "mgr-sophie",
    name: "Sophie Nguyen",
    email: "sophie.nguyen@motelops.au",
    phone: "0401 667 334",
    location: "Shepparton, VIC",
    state: "VIC",
    lat: -36.3778,
    lng: 145.4011,
    photoUrl: portrait("photo-1494790108377-be9c29b29330"),
    bio: "Cloudbeds specialist with restaurant attached motels. Calm under coach-group arrivals and meticulous night audit.",
    rightToWork: "Permanent Resident",
    experience: "3-5 years",
    profileType: "Solo",
    preferredLocations: ["VIC", "NSW", "SA"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["VIC"],
    eventsExperience: true,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["Cloudbeds", "SiteMinder", "Little Hotelier"],
    softwarePOS: ["Lightspeed", "Toast"],
    softwareHR: ["Employment Hero", "Deputy"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-s1",
        businessName: "Goulburn Valley Motor Inn",
        contactPerson: "Rita Bell",
        phone: "03 5831 4400",
        email: "rita@gvmotel.com.au",
        status: "Verified",
      },
      {
        id: "ref-s2",
        businessName: "Echuca River Lodge",
        contactPerson: "Mark Pell",
        phone: "03 5482 1188",
        email: "mark@echucariverlodge.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-11-20", "2026-11-21"],
    completedShifts: 17,
  },
  {
    id: "mgr-hartley",
    name: "Tom Hartley",
    email: "tom.ella@goldfieldsmanagers.au",
    phone: "0429 104 882",
    location: "Kalgoorlie, WA",
    state: "WA",
    lat: -30.7489,
    lng: 121.465,
    photoUrl: portrait("photo-1472099645785-5658abf4ff4e"),
    bio: "FIFO-friendly couple covering Goldfields and Mid West motels. Strong on FIFO check-in peaks and contractor accounts.",
    rightToWork: "Australian Citizen",
    experience: "5+ years",
    profileType: "Couple",
    partnerName: "Ella Hartley",
    partnerBio: "Housekeeping systems, linen control and breakfast for 40+ rooms.",
    partnerExperience: "3-5 years",
    partnerPhotoUrl: portrait("photo-1438761681033-6461ffad8d80"),
    partnerRightToWork: "Australian Citizen",
    preferredLocations: ["WA", "SA", "NT"],
    preferredJobTypes: ["Relief Couple", "Permanent Couple", "Relief"],
    liquorLicensing: true,
    liquorStates: ["WA"],
    eventsExperience: false,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["RMS", "Resly", "SiteMinder"],
    softwarePOS: ["Impos"],
    softwareHR: ["FoundU", "Xero Payroll"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-h1",
        businessName: "Hannans Motor Hotel",
        contactPerson: "Colin West",
        phone: "08 9021 3111",
        email: "colin@hannansmh.com.au",
        status: "Verified",
      },
      {
        id: "ref-h2",
        businessName: "Esperance Bay Motel",
        contactPerson: "Nina Shaw",
        phone: "08 9071 2220",
        email: "nina@esperancebaymotel.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-09-01", "2026-09-02"],
    completedShifts: 21,
  },
  {
    id: "mgr-nathan",
    name: "Nathan Crowe",
    email: "nathan.crowe@reliefmanagers.au",
    phone: "0477 901 226",
    location: "Rockhampton, QLD",
    state: "QLD",
    lat: -23.3791,
    lng: 150.51,
    photoUrl: portrait("photo-1506794778202-cad84cf45f1d"),
    bio: "Events and cattle-sale week specialist. Used to 100% occupancy spikes and live-in owner relief across Capricornia.",
    rightToWork: "Australian Citizen",
    experience: "5+ years",
    profileType: "Solo",
    preferredLocations: ["QLD", "NT"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["QLD", "NT"],
    eventsExperience: true,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["GuestPoint", "Booking247", "RMS"],
    softwarePOS: ["H&L", "Idealpos"],
    softwareHR: ["Deputy"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-n1",
        businessName: "Capricorn Motel",
        contactPerson: "Joanne Lee",
        phone: "07 4927 3300",
        email: "jo@capricornmotel.com.au",
        status: "Verified",
      },
      {
        id: "ref-n2",
        businessName: "Yeppoon Beach Motor Inn",
        contactPerson: "Troy Adams",
        phone: "07 4939 1102",
        email: "troy@yeppoonmotorinn.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-08-28", "2026-08-29"],
    completedShifts: 24,
  },
  {
    id: "mgr-aisha",
    name: "Aisha Rahman",
    email: "aisha.rahman@moteldesk.au",
    phone: "0415 772 019",
    location: "Port Augusta, SA",
    state: "SA",
    lat: -32.49,
    lng: 137.763,
    photoUrl: portrait("photo-1580489944761-15a19d654956"),
    bio: "Cross-border relief across SA and the NT. Precise on fuel-account billing and coach group manifests.",
    rightToWork: "Australian Citizen",
    experience: "3-5 years",
    profileType: "Solo",
    preferredLocations: ["SA", "NT", "WA"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: false,
    liquorStates: [],
    eventsExperience: false,
    restaurantPubExperience: false,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["GuestPoint", "Little Hotelier"],
    softwarePOS: ["Square"],
    softwareHR: ["Tanda", "Xero Payroll"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: false },
    references: [
      {
        id: "ref-a1",
        businessName: "Flinders Ranges Motor Inn",
        contactPerson: "Helen Frost",
        phone: "08 8642 2700",
        email: "helen@flindersmotorinn.com.au",
        status: "Verified",
      },
      {
        id: "ref-a2",
        businessName: "Whyalla Travellers Rest",
        contactPerson: "Ian Brooks",
        phone: "08 8645 1120",
        email: "ian@whyallatr.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: [],
    completedShifts: 14,
  },
  {
    id: "mgr-liam",
    name: "Liam O'Connor",
    email: "liam.oconnor@tasrelief.au",
    phone: "0499 210 443",
    location: "Launceston, TAS",
    state: "TAS",
    lat: -41.4332,
    lng: 147.1441,
    photoUrl: portrait("photo-1519085360753-af0119f7cbe7"),
    bio: "Tasmanian relief covering winter ski-adjacent motels and east-coast summer peaks. References in progress.",
    rightToWork: "Australian Citizen",
    experience: "1-2 years",
    profileType: "Solo",
    preferredLocations: ["TAS", "VIC"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["TAS"],
    eventsExperience: false,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: false, Outlook: true, Teams: false },
    softwarePMS: ["Cloudbeds", "Resly"],
    softwarePOS: ["Lightspeed"],
    softwareHR: ["Deputy"],
    compliance: { policeCheck: true, referenceList: false, managerLicense: false },
    references: [
      {
        id: "ref-l1",
        businessName: "Tamar Valley Motel",
        contactPerson: "Bec Shaw",
        phone: "03 6331 2288",
        email: "bec@tamarvalleymotel.com.au",
        status: "Pending",
      },
    ],
    isVerified: false,
    blockoutDates: ["2026-12-31"],
    completedShifts: 1,
  },
  {
    id: "mgr-whitfield",
    name: "Grace Whitfield",
    email: "grace.ben@newenglandmanagers.au",
    phone: "0422 609 771",
    location: "Tamworth, NSW",
    state: "NSW",
    lat: -31.0927,
    lng: 150.927,
    photoUrl: portrait("photo-1487412720507-e7ab37603c6f"),
    bio: "Country Music Festival veterans. Couple cover for 30–60 room properties with live-in quarters and bottle shop.",
    rightToWork: "Australian Citizen",
    experience: "5+ years",
    profileType: "Couple",
    partnerName: "Ben Whitfield",
    partnerBio: "Maintenance, pool plant and breakfast service. NSW RSA.",
    partnerExperience: "5+ years",
    partnerPhotoUrl: portrait("photo-1507591064344-4c6ce005b128"),
    partnerRightToWork: "Australian Citizen",
    preferredLocations: ["NSW", "QLD", "ACT"],
    preferredJobTypes: ["Relief Couple", "Permanent Couple"],
    liquorLicensing: true,
    liquorStates: ["NSW"],
    eventsExperience: true,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["GuestPoint", "RMS", "Booking247"],
    softwarePOS: ["H&L"],
    softwareHR: ["Deputy", "Employment Hero"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-w1",
        businessName: "Peel Street Motor Inn",
        contactPerson: "Sandra King",
        phone: "02 6766 2211",
        email: "sandra@peelstreetmi.com.au",
        status: "Verified",
      },
      {
        id: "ref-w2",
        businessName: "Armidale City Motel",
        contactPerson: "Greg Holt",
        phone: "02 6772 3388",
        email: "greg@armidalecitymotel.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-09-18", "2026-09-19", "2026-09-20"],
    completedShifts: 19,
  },
  {
    id: "mgr-diego",
    name: "Diego Santos",
    email: "diego.santos@hospitality.au",
    phone: "0455 118 902",
    location: "Mildura, VIC",
    state: "VIC",
    lat: -34.2082,
    lng: 142.1246,
    photoUrl: portrait("photo-1508214751196-bcfd4ca60f91"),
    bio: "Bilingual front office. Restricted work-rights visa with unrestricted hours currently held. RMS and SiteMinder daily user.",
    rightToWork: "Visa with unrestricted work rights",
    experience: "3-5 years",
    profileType: "Solo",
    preferredLocations: ["VIC", "SA", "NSW"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["VIC", "SA"],
    eventsExperience: false,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["RMS", "SiteMinder", "Cloudbeds"],
    softwarePOS: ["Impos", "Square"],
    softwareHR: ["Tanda"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: false },
    references: [
      {
        id: "ref-d1",
        businessName: "Sunraysia Motor Lodge",
        contactPerson: "Patrice Young",
        phone: "03 5023 4411",
        email: "patrice@sunraysiaml.com.au",
        status: "Verified",
      },
      {
        id: "ref-d2",
        businessName: "Wentworth River Motel",
        contactPerson: "Hugh Daly",
        phone: "03 5027 3301",
        email: "hugh@wentworthmotel.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-10-10"],
    completedShifts: 11,
  },
  {
    id: "mgr-mei",
    name: "Mei Lin",
    email: "mei.lin@capmanagers.au",
    phone: "0408 334 671",
    location: "Bundaberg, QLD",
    state: "QLD",
    lat: -24.8661,
    lng: 152.3489,
    photoUrl: portrait("photo-1531123897727-8f129e1688ce"),
    bio: "Five-plus years in sugar-belt and coastal motels. Known for error-free channel mapping and breakfast cost control.",
    rightToWork: "Australian Citizen",
    experience: "5+ years",
    profileType: "Solo",
    preferredLocations: ["QLD", "Nationwide"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["QLD"],
    eventsExperience: true,
    restaurantPubExperience: false,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["GuestPoint", "Cloudbeds", "SiteMinder"],
    softwarePOS: ["Idealpos"],
    softwareHR: ["Deputy", "Xero Payroll"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-m1",
        businessName: "Bargara Beach Motel",
        contactPerson: "Lyn Porter",
        phone: "07 4159 2200",
        email: "lyn@bargaramotel.com.au",
        status: "Verified",
      },
      {
        id: "ref-m2",
        businessName: "Gin Gin Highway Inn",
        contactPerson: "Craig Bell",
        phone: "07 4157 3304",
        email: "craig@ginginhighwayinn.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: [],
    completedShifts: 32,
  },
  {
    id: "mgr-chris",
    name: "Chris Parker",
    email: "chris.parker@outbackrelief.au",
    phone: "0427 556 810",
    location: "Broken Hill, NSW",
    state: "NSW",
    lat: -31.9539,
    lng: 141.4536,
    photoUrl: portrait("photo-1463453091185-61582044d556"),
    bio: "Remote-area relief including NT roadhouses attached to motels. Comfortable with satellite internet and owner absence of 6+ weeks.",
    rightToWork: "Australian Citizen",
    experience: "5+ years",
    profileType: "Solo",
    preferredLocations: ["NSW", "NT", "SA"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["NSW", "NT"],
    eventsExperience: false,
    restaurantPubExperience: true,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: false },
    softwarePMS: ["Booking247", "RMS"],
    softwarePOS: ["H&L"],
    softwareHR: ["FoundU"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-c1",
        businessName: "Barrier Highway Motel",
        contactPerson: "Sue Maguire",
        phone: "08 8088 4410",
        email: "sue@barrierhighwaymotel.com.au",
        status: "Verified",
      },
      {
        id: "ref-c2",
        businessName: "Alice Tourist Apartments",
        contactPerson: "Dan Cole",
        phone: "08 8952 7788",
        email: "dan@alicetourist.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-09-05"],
    completedShifts: 22,
  },
  {
    id: "mgr-olivia",
    name: "Olivia Grant",
    email: "olivia.grant@capitalrelief.au",
    phone: "0413 990 228",
    location: "Canberra, ACT",
    state: "ACT",
    lat: -35.2809,
    lng: 149.13,
    photoUrl: portrait("photo-1524504388940-b1c1722653e1"),
    bio: "Parliamentary sitting-week cover and NSW southern tablelands relief. Opera and Cloudbeds dual competent.",
    rightToWork: "Australian Citizen",
    experience: "3-5 years",
    profileType: "Solo",
    preferredLocations: ["ACT", "NSW", "VIC"],
    preferredJobTypes: ["Relief", "Full-Time"],
    liquorLicensing: true,
    liquorStates: ["ACT", "NSW"],
    eventsExperience: true,
    restaurantPubExperience: false,
    microsoftOffice: { Word: true, Excel: true, Outlook: true, Teams: true },
    softwarePMS: ["Opera", "Cloudbeds", "SiteMinder"],
    softwarePOS: ["Lightspeed"],
    softwareHR: ["Employment Hero"],
    compliance: { policeCheck: true, referenceList: true, managerLicense: true },
    references: [
      {
        id: "ref-o1",
        businessName: "Braddon Motor Lodge",
        contactPerson: "Peter Walsh",
        phone: "02 6248 1100",
        email: "peter@braddonml.com.au",
        status: "Verified",
      },
      {
        id: "ref-o2",
        businessName: "Queanbeyan Highway Motel",
        contactPerson: "Amy Cho",
        phone: "02 6297 4411",
        email: "amy@qbnmotel.com.au",
        status: "Verified",
      },
    ],
    isVerified: true,
    blockoutDates: ["2026-11-03", "2026-11-04"],
    completedShifts: 15,
  },
];

export const seedOwners: OwnerProfile[] = [
  {
    id: "owner-helen",
    name: "Helen Walsh",
    email: "helen@highwayrest.com.au",
    phone: "02 6882 9100",
    motelName: "The Highway Rest",
    location: "Dubbo, NSW",
    state: "NSW",
    photoUrl: portrait("photo-1544005313-94ddf0286df2"),
    rooms: 32,
    pms: "GuestPoint",
    advisoryStack: ["adv-broker-nsw", "adv-tax-nsw"],
    advisoryPromptDismissed: false,
  },
  {
    id: "owner-robert",
    name: "Robert Pike",
    email: "robert@tropictrade.com.au",
    phone: "07 4927 1188",
    motelName: "Tropic Trade Motel",
    location: "Rockhampton, QLD",
    state: "QLD",
    photoUrl: portrait("photo-1560250097-0b93528c311a"),
    rooms: 44,
    pms: "RMS",
    advisoryStack: ["adv-broker-qld", "adv-legal-qld"],
    advisoryPromptDismissed: true,
  },
  {
    id: "owner-janelle",
    name: "Janelle Morris",
    email: "janelle@murrayview.com.au",
    phone: "03 5023 7700",
    motelName: "Murray View Motor Inn",
    location: "Mildura, VIC",
    state: "VIC",
    photoUrl: portrait("photo-1551836022-d5d88e9218df"),
    rooms: 28,
    pms: "Cloudbeds",
    advisoryStack: ["adv-finance-1"],
    advisoryPromptDismissed: true,
  },
  {
    id: "owner-frank",
    name: "Frank DeLuca",
    email: "frank@goldfieldslodge.com.au",
    phone: "08 9021 6644",
    motelName: "Goldfields Lodge",
    location: "Kalgoorlie, WA",
    state: "WA",
    photoUrl: portrait("photo-1472099645785-5658abf4ff4e"),
    rooms: 38,
    pms: "Resly",
    advisoryStack: ["adv-legal-1", "adv-finance-2"],
    advisoryPromptDismissed: true,
  },
];

export const seedListedRoles: ListedRole[] = [
  {
    id: "role-helen-relief",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    motelName: "The Highway Rest",
    location: "Dubbo, NSW",
    state: "NSW",
    jobType: "Relief",
    startDate: "2026-09-14",
    endDate: "2026-09-28",
    dailyRate: 400,
    notes: "Live-in relief. Breakfast service and GuestPoint night audit. Dog on site.",
    status: "Open",
    interestedManagerIds: ["mgr-brennan"],
    createdAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "role-robert-couple",
    ownerId: "owner-robert",
    ownerName: "Robert Pike",
    motelName: "Tropic Trade Motel",
    location: "Rockhampton, QLD",
    state: "QLD",
    jobType: "Permanent Couple",
    startDate: "2026-10-06",
    endDate: "2027-10-06",
    dailyRate: 450,
    notes: "44 rooms, RMS, live-in managers unit. Couple preferred for front office and grounds.",
    status: "Open",
    interestedManagerIds: [],
    createdAt: "2026-08-22T00:00:00.000Z",
  },
  {
    id: "role-janelle-relief",
    ownerId: "owner-janelle",
    ownerName: "Janelle Morris",
    motelName: "Murray View Motor Inn",
    location: "Mildura, VIC",
    state: "VIC",
    jobType: "Relief Couple",
    startDate: "2026-11-02",
    endDate: "2026-11-23",
    dailyRate: 420,
    notes: "Owner holiday cover. Cloudbeds, 28 rooms, river trade.",
    status: "Open",
    interestedManagerIds: ["mgr-sophie"],
    createdAt: "2026-08-24T00:00:00.000Z",
  },
];

export const seedContracts: JobContract[] = [
  {
    id: "job-completed-brennan",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    managerId: "mgr-brennan",
    managerName: "Marcus & Priya Brennan",
    startDate: "2026-06-02",
    endDate: "2026-06-23",
    dailyRate: 420,
    contractDetails:
      "Owner holiday cover. Live-in managers unit, breakfast 6:30–9:00, night audit in GuestPoint.",
    specialConditions: "Dog on site. No smoking in managers residence.",
    status: "Completed",
    ownerSignedNDA: true,
    managerSignedNDA: true,
    ownerAgreed: true,
    managerAgreed: true,
    messages: [
      {
        id: "m1",
        senderId: "owner-helen",
        sender: "Helen Walsh",
        text: "Dates locked. Linen delivery is Tuesdays.",
        timestamp: "2026-05-20T09:12:00",
      },
      {
        id: "m2",
        senderId: "mgr-brennan",
        sender: "Marcus Brennan",
        text: "Noted. We'll arrive the afternoon prior to walk through.",
        timestamp: "2026-05-20T09:40:00",
      },
    ],
    reviewByOwner: {
      overall: 9,
      guestService: 10,
      computerCapability: 9,
      attentionToDetail: 9,
      rehire: true,
      comments: "GuestPoint night audits were perfect. Would rehire immediately.",
    },
    reviewByManager: {
      residence: 8,
      environment: 9,
      wagesPaidSwiftly: 10,
      comments: "Residence tidy. Paid within 48 hours of invoice.",
    },
    disputed: false,
  },
  {
    id: "job-agreed-whitfield",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    managerId: "mgr-whitfield",
    managerName: "Grace & Ben Whitfield",
    startDate: "2026-10-04",
    endDate: "2026-10-18",
    dailyRate: 440,
    contractDetails: "Country Music Festival overflow cover plus breakfast.",
    specialConditions: "Bottle shop RSA required.",
    status: "Agreed",
    ownerSignedNDA: true,
    managerSignedNDA: true,
    ownerAgreed: true,
    managerAgreed: true,
    messages: [
      {
        id: "m3",
        senderId: "owner-helen",
        sender: "Helen Walsh",
        text: "Festival week will be 100%. Extra housekeeper booked.",
        timestamp: "2026-08-02T11:00:00",
      },
    ],
    disputed: false,
  },
  {
    id: "job-chat-mei",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    managerId: "mgr-mei",
    managerName: "Mei Lin",
    startDate: "2026-11-08",
    endDate: "2026-11-22",
    dailyRate: 390,
    contractDetails: "Solo relief while owners attend a family wedding.",
    specialConditions: "Must be GuestPoint competent.",
    status: "ChatActive",
    ownerSignedNDA: true,
    managerSignedNDA: true,
    ownerAgreed: false,
    managerAgreed: false,
    messages: [
      {
        id: "m4",
        senderId: "owner-helen",
        sender: "Helen Walsh",
        text: "Could you do $390/day including breakfast?",
        timestamp: "2026-08-18T14:22:00",
      },
      {
        id: "m5",
        senderId: "mgr-mei",
        sender: "Mei Lin",
        text: "Yes if the managers unit is available those dates.",
        timestamp: "2026-08-18T16:01:00",
      },
    ],
    disputed: false,
  },
  {
    id: "job-nda-nathan",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    managerId: "mgr-nathan",
    managerName: "Nathan Crowe",
    startDate: "2027-01-05",
    endDate: "2027-01-26",
    dailyRate: 410,
    contractDetails: "January relief. Cattle sale week in the middle.",
    specialConditions: "Liquor license QLD preferred.",
    status: "NDAPending",
    ownerSignedNDA: true,
    managerSignedNDA: false,
    ownerAgreed: false,
    managerAgreed: false,
    messages: [],
    disputed: false,
  },
  {
    id: "job-proposal-sophie",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    managerId: "mgr-sophie",
    managerName: "Sophie Nguyen",
    startDate: "2026-12-01",
    endDate: "2026-12-14",
    dailyRate: 400,
    contractDetails: "December shoulder-season cover.",
    specialConditions: "",
    status: "Proposal",
    ownerSignedNDA: false,
    managerSignedNDA: false,
    ownerAgreed: false,
    managerAgreed: false,
    messages: [],
    disputed: false,
  },
  {
    id: "job-completed-mei-robert",
    ownerId: "owner-robert",
    ownerName: "Robert Pike",
    ownerMotel: "Tropic Trade Motel",
    managerId: "mgr-mei",
    managerName: "Mei Lin",
    startDate: "2026-04-06",
    endDate: "2026-04-27",
    dailyRate: 405,
    contractDetails: "Beef Expo week plus following fortnight.",
    specialConditions: "",
    status: "Completed",
    ownerSignedNDA: true,
    managerSignedNDA: true,
    ownerAgreed: true,
    managerAgreed: true,
    messages: [],
    reviewByOwner: {
      overall: 10,
      guestService: 10,
      computerCapability: 10,
      attentionToDetail: 9,
      rehire: true,
      comments: "Best Expo week we have had. Channel mapping was flawless.",
    },
    reviewByManager: {
      residence: 7,
      environment: 8,
      wagesPaidSwiftly: 9,
      comments: "Residence dated but functional. Paid on time.",
    },
    disputed: false,
  },
  {
    id: "job-completed-nathan-robert",
    ownerId: "owner-robert",
    ownerName: "Robert Pike",
    ownerMotel: "Tropic Trade Motel",
    managerId: "mgr-nathan",
    managerName: "Nathan Crowe",
    startDate: "2026-02-09",
    endDate: "2026-03-02",
    dailyRate: 415,
    contractDetails: "Owner medical leave.",
    specialConditions: "",
    status: "Completed",
    ownerSignedNDA: true,
    managerSignedNDA: true,
    ownerAgreed: true,
    managerAgreed: true,
    messages: [
      {
        id: "m6",
        senderId: "owner-robert",
        sender: "Robert Pike",
        text: "Bar takings were short on Saturday night.",
        timestamp: "2026-03-04T08:11:00",
      },
    ],
    reviewByOwner: {
      overall: 6,
      guestService: 8,
      computerCapability: 7,
      attentionToDetail: 5,
      rehire: false,
      comments: "Guests loved him. Variance on bottle shop unsettled us.",
    },
    reviewByManager: {
      residence: 6,
      environment: 7,
      wagesPaidSwiftly: 6,
      comments: "Invoice sat for 11 days. Residence A/C failed mid stay.",
    },
    disputed: true,
    disputeNote: "Owner alleges bottle-shop variance; manager disputes till training.",
    disputeStatus: "Open",
  },
  {
    id: "job-declined",
    ownerId: "owner-janelle",
    ownerName: "Janelle Morris",
    ownerMotel: "Murray View Motor Inn",
    managerId: "mgr-diego",
    managerName: "Diego Santos",
    startDate: "2026-09-07",
    endDate: "2026-09-21",
    dailyRate: 360,
    contractDetails: "Shoulder relief.",
    specialConditions: "",
    status: "Declined",
    ownerSignedNDA: false,
    managerSignedNDA: false,
    ownerAgreed: false,
    managerAgreed: false,
    messages: [],
    disputed: false,
  },
  {
    id: "job-completed-hartley",
    ownerId: "owner-frank",
    ownerName: "Frank DeLuca",
    ownerMotel: "Goldfields Lodge",
    managerId: "mgr-hartley",
    managerName: "Tom & Ella Hartley",
    startDate: "2026-05-04",
    endDate: "2026-06-01",
    dailyRate: 450,
    contractDetails: "FIFO peak month.",
    specialConditions: "Contractor accounts in RMS.",
    status: "Completed",
    ownerSignedNDA: true,
    managerSignedNDA: true,
    ownerAgreed: true,
    managerAgreed: true,
    messages: [],
    reviewByOwner: {
      overall: 9,
      guestService: 8,
      computerCapability: 9,
      attentionToDetail: 9,
      rehire: true,
      comments: "Handled 6am FIFO departures without a hitch.",
    },
    reviewByManager: {
      residence: 9,
      environment: 8,
      wagesPaidSwiftly: 9,
      comments: "Residence excellent. Paid weekly as agreed.",
    },
    disputed: false,
  },
];

export const seedAdvisors: AdvisorProfile[] = [
  {
    id: "adv-broker-nsw",
    name: "Catherine Boyle",
    practiceName: "Regional Inn Sales",
    category: "Motel Broker",
    statesCovered: ["NSW", "ACT", "QLD"],
    location: "Orange, NSW",
    lat: -33.2839,
    lng: 149.1003,
    phone: "02 6362 4410",
    email: "catherine@regionalinnsales.com.au",
    website: "https://regionalinnsales.com.au",
    specialtyTags: ["Highway motels", "Leasehold", "Freehold going concern"],
    photoUrl: portrait("photo-1573497019940-1c28c88b4f3e"),
    bio: "Highway and regional motel sales across western NSW. Direct owner introductions — no lead desk, no percentage cut to Motel Connect.",
  },
  {
    id: "adv-broker-qld",
    name: "Mick Hanley",
    practiceName: "Coastal Motel Brokers",
    category: "Motel Broker",
    statesCovered: ["QLD", "NSW"],
    location: "Sunshine Coast, QLD",
    lat: -26.65,
    lng: 153.0667,
    phone: "07 5443 2211",
    email: "mick@coastalmotelbrokers.com.au",
    website: "https://coastalmotelbrokers.com.au",
    specialtyTags: ["Coastal", "20–50 rooms", "Management rights"],
    photoUrl: portrait("photo-1556157382-97eda2d62296"),
    bio: "Coastal and hinterland motel going concerns. Qualifies buyers before they ever ring the front desk.",
  },
  {
    id: "adv-legal-1",
    name: "Priya Desai",
    practiceName: "Hospitality Legal Partners",
    category: "Lawyer & Legal",
    statesCovered: ["NSW", "VIC", "QLD", "WA", "SA"],
    location: "Sydney, NSW",
    lat: -33.8688,
    lng: 151.2093,
    phone: "02 9251 8800",
    email: "priya@hlpartners.com.au",
    website: "https://hlpartners.com.au",
    specialtyTags: ["Sale contracts", "Liquor licensing", "Lease disputes"],
    photoUrl: portrait("photo-1551836022-deb4988cc6c0"),
    bio: "Sale contracts, liquor licensing and lease disputes written for motel operators, not CBD developers.",
  },
  {
    id: "adv-legal-qld",
    name: "Andrew Holt",
    practiceName: "Holt Hospitality Law",
    category: "Lawyer & Legal",
    statesCovered: ["QLD", "NT"],
    location: "Brisbane, QLD",
    lat: -27.4698,
    lng: 153.0251,
    phone: "07 3221 4090",
    email: "andrew@holthlaw.com.au",
    website: "https://holthlaw.com.au",
    specialtyTags: ["Freehold sale", "Body corporate", "Employment"],
    photoUrl: portrait("photo-1566492031773-4f4e44671857"),
    bio: "Queensland freehold sales, body corporate and employment law for live-in motel businesses.",
  },
  {
    id: "adv-tax-nsw",
    name: "Elena Rossi",
    practiceName: "Motel Tax Advisory",
    category: "Accountant & Tax",
    statesCovered: ["NSW", "ACT", "VIC"],
    location: "Parramatta, NSW",
    lat: -33.815,
    lng: 151.001,
    phone: "02 9635 1188",
    email: "elena@moteltax.com.au",
    website: "https://moteltax.com.au",
    specialtyTags: ["BAS", "CGT motels", "Trust structures"],
    photoUrl: portrait("photo-1580489944761-15a19d654956"),
    bio: "CGT, managers-unit FBT and trust structures without having to explain what a motel actually is.",
  },
  {
    id: "adv-tax-qld",
    name: "David Chen",
    practiceName: "Capricorn Hospitality Accountants",
    category: "Accountant & Tax",
    statesCovered: ["QLD", "NT"],
    location: "Toowoomba, QLD",
    lat: -27.5598,
    lng: 151.9507,
    phone: "07 4632 9090",
    email: "david@capaccountants.com.au",
    website: "https://capaccountants.com.au",
    specialtyTags: ["Payroll", "FBT managers units", "Stocktakes"],
    photoUrl: portrait("photo-1507003211169-0a1dd7228f2d"),
    bio: "Payroll, stocktakes and FBT on managers units for regional Queensland motels.",
  },
  {
    id: "adv-finance-1",
    name: "Sarah McLeod",
    practiceName: "AgriMotel Finance",
    category: "Finance & Refinancing",
    statesCovered: ["VIC", "SA", "NSW", "QLD"],
    location: "Bendigo, VIC",
    lat: -36.757,
    lng: 144.2794,
    phone: "03 5441 2200",
    email: "sarah@agrimotelfinance.com.au",
    website: "https://agrimotelfinance.com.au",
    specialtyTags: ["Refinancing", "Going concern lending", "Equipment"],
    photoUrl: portrait("photo-1548142813-c348350df52b"),
    bio: "Going-concern lending and refinance for highway motels. Speaks both bank and breakfast-service.",
  },
  {
    id: "adv-finance-2",
    name: "James Okonkwo",
    practiceName: "Goldfields Commercial Lending",
    category: "Finance & Refinancing",
    statesCovered: ["WA", "NT", "SA"],
    location: "Perth, WA",
    lat: -31.9505,
    lng: 115.8605,
    phone: "08 9221 3344",
    email: "james@gclending.com.au",
    website: "https://gclending.com.au",
    specialtyTags: ["FIFO motels", "Construction drawdowns", "Refinance"],
    photoUrl: portrait("photo-1519085360753-af0119f7cbe7"),
    bio: "FIFO motel refinance and construction drawdowns across WA, the NT and the far west.",
  },
];

export const seedAdvisorReviews: AdvisorReview[] = [
  {
    id: "ar-1",
    advisorId: "adv-broker-nsw",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    region: "NSW",
    serviceProvided: "Buying",
    rating: 5,
    feedback: "Straight talk on highway traffic counts. No lead-fee nonsense.",
    date: "2025-11-12",
    isVerifiedOwner: true,
  },
  {
    id: "ar-2",
    advisorId: "adv-tax-nsw",
    ownerId: "owner-helen",
    ownerName: "Helen Walsh",
    ownerMotel: "The Highway Rest",
    region: "NSW",
    serviceProvided: "Tax",
    rating: 4,
    feedback: "Understood managers-unit FBT without us having to explain motel life.",
    date: "2026-02-03",
    isVerifiedOwner: true,
  },
  {
    id: "ar-3",
    advisorId: "adv-broker-qld",
    ownerId: "owner-robert",
    ownerName: "Robert Pike",
    ownerMotel: "Tropic Trade Motel",
    region: "QLD",
    serviceProvided: "Selling",
    rating: 5,
    feedback: "Qualified buyers only. Saved us from tyre-kickers.",
    date: "2026-01-20",
    isVerifiedOwner: true,
  },
  {
    id: "ar-4",
    advisorId: "adv-finance-1",
    ownerId: "owner-janelle",
    ownerName: "Janelle Morris",
    ownerMotel: "Murray View Motor Inn",
    region: "VIC",
    serviceProvided: "Refinancing",
    rating: 5,
    feedback: "Cut 70 points off our rate. Spoke bank language and motel language.",
    date: "2026-03-14",
    isVerifiedOwner: true,
  },
  {
    id: "ar-5",
    advisorId: "adv-legal-1",
    ownerId: "owner-frank",
    ownerName: "Frank DeLuca",
    ownerMotel: "Goldfields Lodge",
    region: "WA",
    serviceProvided: "Legal",
    rating: 4,
    feedback: "Lease variation done properly. A little slow on emails.",
    date: "2025-09-08",
    isVerifiedOwner: true,
  },
];

export function createInitialState(): AppState {
  return {
    managers: seedManagers,
    owners: seedOwners,
    contracts: seedContracts,
    listedRoles: seedListedRoles,
    advisors: seedAdvisors,
    advisorReviews: seedAdvisorReviews,
    taxonomy: defaultTaxonomy,
    waitlist: [],
    session: null,
  };
}
